### ISSUE TITLE
Windows 10 下 lemon 需管理员权限运行，否则评测时会CE

### ISSUE THREAD

**Issue by Prurite** [Dust1404/Project_LemonPlus#2]
如题，在评测选手程序时报编译错误：`Cannot create temporary file in C:\Windows\: Permission denied` ，而作为一个评测工具其本身不应需要管理员权限，请考虑将临时文件存放地址移到 `%TEMP%` 下。

**Comment by Dust1404** [comment]
暂时可以在编译器设置中添加环境变量解决此问题。
将在下次更新时解决默认临时目录的问题。
