### ISSUE TITLE
希望提供帮助文档

### ISSUE THREAD

**Issue by Prurite** [Dust1404/Project_LemonPlus#3]
如题，这个版本的lemon相较原版lemon有了较大更新和改变，网上也较难搜索到该版本的相关教程，建议提供内建帮助（至少是对于新功能的）。完善的文档也有助于软件的推广，毕竟原版lemon已有数年未更新，无法适应时代需求，此版本lemon有成为下一个时代标杆的潜力。

**Comment by HopleViorn** [comment]
+1

**Comment by iotang** [comment]
把 LemonPt 的帮助合并如何？

**Comment by Dust1404** [comment]
> 把 LemonPt 的帮助合并如何？

可行，除此之外我最近会写一个 pdf 版的用户手册。

**Comment by iotang** [comment]
LemonPt 的 用户手册(Markdown) 正在做了

**Comment by Prurite** [comment]
建议把帮助做成markdown版本，github上一份，release里也附带一份

**Comment by Dust1404** [comment]
用户手册已上传，如果有没提到的问题可以开新的 Issue。
